apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin.registrykey
  namespace: cp4ba
spec:
  encryptedData:
    .dockerconfigjson: AgAO8KZ/ov4An8Nsa5eZMyDfFx6qW8vzU+xncJL/ylkNdsEPlrhZ7w4hsm1xuotu+YVuNC+oNwvMEbtPPxEwe2fpaadfbIzC4KQc5pYPsyCfaREwGiWLvG9TczQ+9UQGS9fmT2CkQaHpQnFN4oaAM6SFkh97ZRSrwCLyCnIxRv7W2ChPYcEdzZkN1gRUd7xXeKipTHW9AoKNpsDwNH6Qw95YpQh0S/YUYu7WQmKwBOusNl91PdvLBJ/O8quaBmIJ2y/mrjUJGaHR6anA/aVHlHeEIERm5mVhVecaCPLWjnrcrIKW9m9hhHRAHc7fMjarJnK19JrhpANbapIC9mdAK9GHIcor3hXWQQ/AlDSgrq6g5ZRy6nk8DpfEFmsKhpXoc6cnVa4Qjb15iXLeKocUHItTCLt7tfr1SIHyIUR8NudWMSPkFNcxoG5JeXJ8REeMjfxkNuj8mHN7u9RyMj7o1qb5dJpOPlCfA7O5V3oe5g+/oj2h3DLQT1T9l7oHFQASIakTJjkpJoFegNsfhTKEvG6YaOwmYFC3fFh2S/YPzvznQUWGuq3jLz6K27OEvkULtt7D5uTr+A9xO2wxFnXXnygvgnv4Ouu0zWo8Wmz46see+jHPEjA4dgX4/pCcxyIGhHzcFqoZqtYg1E4y3tbkeEvu/c4Akr2pNJSuF24OJAb/R/TPq1tlNCLYliVmg/U2lPV7iGDsw37QoGw+PlkyF0xweNYCLhHIvDUA2ttCPM4arAMPXVh11p68VBPSDTDyBtK2KbN1pqVHApFIfBx16/2ztixuaSldp5SlSTx4pO/AP06xUz4xPO7P1JSnqf3V7yl365kGPdS0oBoJBnSQ0+1oU9l3zHELkuWlQDOUGfS0AYMEqowG/O6pHicBk9FVPTDeVwMuottYaj/IBQVOkVPOKT0uqOpb5jERMDTXDmosscYSy3h8dYhQB10N3I49Fe0XF7WFhy8tiNRhlx3iEw1lnHf53C36kUrHapJTRY/xZMaNKdc7i9AlwMhQa2205zSJeW92jzOWRJwf65a42XUhVQcaDxtfAFkIR4uEPo8pbo9oZwkH1X1H6GjKb8UavjM8jfx/U6MyvgD6w+ftGEcc391fcqTkAk99Zm7iz63KgzNWaERNsvvoO+Y9IVWo4nUOU2gJ6rVog3FltZf81PWz6Fyr4ovArtKNT9YcwpOjlTcMqjbe+fik9jMCS0oltjsXMAMIQXDAmqaiyMjbGTsGXXAjOgFo1OFWfwBHPBggnnZ7Hw8/OXdeShsK879V/stkiF8xl8DNzCmIqW06UuWHJuSJlDwN6aI6TYSdqBRJcNfXIUK6FrlGmrtjfMlwfpkQtKW1waZx7oBbT+zR5DISKDHxa/rXy5WcCXxugL5ygUamcdsO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: admin.registrykey
      namespace: cp4ba
    type: kubernetes.io/dockerconfigjson

